#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

PATH=$PATH:/usr/bin/core_perl
PATH=$PATH:~/.gem/ruby/2.4.0/bin
PATH=$PATH:~/.local/bin
PATH=$PATH:~/bin

export QT_STYLE_OVERRIDE=breeze
export QT_AUTO_SCREEN_SCALE_FACTOR=0

export OPAMUTF8MSGS=1

PATH=$HOME/.node_modules/bin:$PATH
export npm_config_prefix=~/.node_modules

PATH=$HOME/.emacs.d/bin:$PATH
