#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

PATH=$PATH:/usr/bin/core_perl
PATH=$PATH:~/.gem/ruby/2.4.0/bin
PATH=$PATH:~/.local/bin
PATH=$PATH:~/bin

QT_STYLE_OVERRIDE=breeze
QT_QPA_PLATFORMTHEME="qt5ct"
QT_AUTO_SCREEN_SCALE_FACTOR=0

export OPAMUTF8MSGS=1