#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload bashcompinit
bashcompinit

# OPAM configuration
test -r /home/lelio/.opam/opam-init/init.zsh && . /home/lelio/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

alias ouu='opam update -u'
alias ouus='opam update; for s in $(opam switch list -s | head -n -1); do printf "\nupgrading $s switch...\n"; opam upgrade --switch=$s; done'
alias osw='opam switch'
alias oce='eval `opam env`'
alias oss='opam switch show'

alias la='ls -A'
alias lal='la -lh'

alias pacc='pac -Sc'

alias xdg-wrap='ocaml ${HOME}/.scripts/xdg-wrap.ml'

alias tab='qpdfview --unique'

alias gcfg='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

alias checklibs="sudo lsof +c 0 | grep 'DEL.*lib' | awk '1 { print \$1 \": \" \$NF }' | sort -u"

alias tlmgr-wrap='ocaml ${HOME}/.scripts/tlmgr.ml'

# alias tlmgr_search='tlmgr search --global --file'
# alias tlmgr_install='tlmgr install'
# alias tlmgr_update='tlmgr update --self --all && tlmgr path add && fmtutil-sys --all'

# added by travis gem
[ -f /home/lelio/.travis/travis.sh ] && source /home/lelio/.travis/travis.sh

# keybase completion
test -r /home/lelio/.keybase-completion/keybase && source $_
